# Generated by Django 2.2 on 2019-12-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191206_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(max_length=255, null=True, verbose_name='Apellido usuario'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre usuario'),
        ),
    ]
