# Generated by Django 2.2 on 2019-12-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=255, null=True, verbose_name='Nombre cat')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mesa', models.CharField(max_length=255, null=True, verbose_name='Nombre mesa')),
                ('cantidad_asientos', models.IntegerField(null=True, verbose_name='Cantidad asientos')),
            ],
        ),
    ]
